Green.Health/Green.Health/Models/CommonModel.cs
using Green.Health.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Green.Health.Models
{
    public class CommonModel
    {
        public Customer Customer { get; set; }
    }
}

Green.Health/Green.Health/Models/LoginModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Green.Health.Models
{
    public class LoginModel
    {
        public string UserName { get; set; }

        public string Pwd { get; set; }

        public bool RememberMe { get; set; }

    }
}

Green.Health/Green.Health/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Green.Health.Controllers
{
    public abstract class BaseController : Controller
    {
        public BaseController() {
           
        }
    }
}

Green.Health/Green.Health/Controllers/CommonController.cs
using Green.Health.Entity;
using Green.Health.Models;
using Green.Health.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Green.Health.Controllers
{
    public class CommonController : Controller
    {
       public ILoginService _loginService;

       public CommonController(ILoginService loginService) 
        {
            this._loginService = loginService;
        }

        public ActionResult headlink()
        {
            CommonModel cm = new CommonModel();
            cm.Customer = _loginService.GetCustomer();
            return PartialView("_Head",cm);
        }

    }
}

Green.Health/Green.Health/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Green.Health.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Green.Health/Green.Health/Controllers/LoginController.cs
using Green.Health.Entity;
using Green.Health.Models;
using Green.Health.Service;
using Green.Health.Web.Framework.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Green.Health.Controllers
{
    public class LoginController : BaseController
    {
        private ILoginService loginService;

        private ICustomerService authService;

        public LoginController(ILoginService mloginservice, ICustomerService authService)
        {
            this.loginService = mloginservice;
            this.authService = authService;
        }

        //
        // GET: /Login/
        [HttpsRequirement(SslRequirement.YES)]
        public ActionResult Index(LoginModel model)
        {
            return View("LogIn", model);
        }

        [HttpPost]
        public ActionResult LogIn(LoginModel model, string rtnUrl)
        {
            string uid = model.UserName;
            string pwd = model.Pwd;
            LoginResult result = loginService.CheckLogin(uid, pwd);
            Customer customer = authService.GetCustomer(uid);
            switch (result)
            {
                case LoginResult.Success:
                    loginService.SingIn(customer);
                    rtnUrl = HttpUtility.UrlDecode(rtnUrl);
                    if (!string.IsNullOrEmpty(rtnUrl))
                    {
                        return Redirect(rtnUrl);
                    }
                    else
                    {
                        return RedirectToAction("ShowInfo", "Maka");
                    }
                case LoginResult.NotExist:
                    ModelState.AddModelError("UserName", "用户名不存在！");
                    break;
                case LoginResult.PwdError:
                    ModelState.AddModelError("Pwd", "密码输入错误！");
                    break;
                case LoginResult.IsNotActive:
                    ModelState.AddModelError("UserName", "用户未激活！");
                    break;
                default:
                    break;
            }
            return View(model);
        }

        public ActionResult LogOut()
        {
            loginService.SingOut();
            return RedirectToAction("ShowInfo", "Maka");
        }
    }
}

Green.Health/Green.Health/Controllers/MaKaController.cs
using Green.Health.Web.Framework.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Green.Health.Controllers
{
    public class MaKaController : BaseController
    {
        //
        // GET: /MaKa/
        public ActionResult ShowInfo()
        {
           
            return View();
        }

    }
}

Green.Health/Green.Health/Controllers/OrderController.cs
using Green.Health.Service;
using Green.Health.Web.Framework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Green.Health.Controllers
{
    public class OrderController : BaseController
    {
        public ILoginService _loginService;

        public OrderController(ILoginService loginService)
        {
            this._loginService = loginService;
        }

        public ActionResult comfirm_order(int id = 1)
        {
            //如果没有登录，跳转到登录页面
            if (_loginService.GetCustomer() == null)
            {
                string url = HttpUtility.UrlEncode(HttpContext.Request.Url.AbsolutePath);
                return RedirectToAction("Index", "Login", new { rtnUrl = HttpContext.Request.Url });
            }
            //查找显示购物车货物list



            return View();
        }
    }
}

Green.Health/Green.Health/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Green.Health.Controllers
{
    public class ProductController : BaseController
    {
        //
        // GET: /Product/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Detail()
        {
            return View();
        }
    }
}

Green.Health/Green.Health/Controllers/ShopCarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Green.Health.Controllers
{
    public class ShopCarController : Controller
    {
        //
        // GET: /ShopCar/

        public ActionResult AddProduct()
        {
            return View();
        }
    }
}

Green.Health/Green.Health/Views/Login/LogIn.cshtml
@model Green.Health.Models.LoginModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "登录";
}
@section PageSpecificStyleSheetIncludes{
    <style>
        .login-wrap {
            width: 350px;
            display: block;
            padding-top: 150px;
            margin: 0 auto;
        }
        .ng-link-area {
            display: block;
            float: right;
            padding-right: 60px;
            margin-bottom: 15px;
        }
    </style>
}

<div class="frame-container">
    <div class="login-wrap">
        @using (Html.BeginForm("LogIn", "Login", new { rtnUrl = Request.QueryString["rtnurl"] }, FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                <label for="inputEmail3" class="sr-only">User</label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", @placeholder = "手机号" })
                    @Html.ValidationMessageFor(m => m.UserName)
                    @*<input type="text" class="form-control" id="inputUserNo" name="userno" placeholder="手机号">*@
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword3" class="sr-only">Password</label>
                <div class="col-sm-10">
                    @Html.PasswordFor(m => m.Pwd, new { @class = "form-control", @placeholder = "密码" })
                    @Html.ValidationMessageFor(m => m.Pwd)
                    @*<input type="password" class="form-control" id="inputPassword" name="passwd" placeholder="密码">*@
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-10">

                    <button type="submit" class="btn btn-success btn-lg btn-block"> 登录</button>
                </div>
            </div>
            <div class="ng-link-area">
                <span><a href="#">其他登录方式</a></span>
                <span><a href="#">|</a></span>
                <span><a href="#">忘记密码?</a></span>
            </div>
            <div class="form-group">
                <div class="col-sm-10">
                    <a class="btn btn-default btn-lg btn-block">注册账号</a>
                </div>
            </div>
        }
    </div>
</div>

Green.Health/Green.Health/Views/Maka/ShowInfo.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "首页";
}
@section PageSpecificStyleSheetIncludes
{
    <style>
        .imgcontainer {
            width: 100%;
            min-width: 1240px;
            float: left;
            position: relative;
            margin: 80px auto;
            background-color: #fff;
            overflow: hidden;
        }

        img {
            border: none;
            vertical-align: middle;
            max-width: 100%;
        }
    </style>
}
<nav class="subnav">
    <div class="subnav-wrap">
         <h2 class="nav_sub_title">SHI HU</h2>
        <div class="nav_sub_desp">
            @*<a href="#">产品信息</a>
            <span>|</span>
            <a href="#">产地来源</a>
            <span>|</span>
            <a href="#">产品药理</a>*@
            <span class="btn btn-success" id="btnbuy">立即订购</span>
        </div>
    </div>

</nav>
<div class="imgcontainer">
    <p text-align:center;><img src="/Assets/Img/desp6.jpg" /></p>
    <p text-align:center;><img src="/Assets/Img/desp1.jpg" /></p>
    <p text-align:center;><img src="/Assets/Img/desp2.jpg" /></p>
    <p text-align:center;><img src="/Assets/Img/desp3.jpg" /></p>
    <p text-align:center;><img src="/Assets/Img/desp4.jpg" /></p>
    <p text-align:center;><img src="/Assets/Img/desp5.jpg" /></p>
</div>

@section PageSpecificJavascriptIncludes{
   <script>
       $("#btnbuy").bind('click', function (e) {
           window.location.href = "/Product/Detail";
       });
    </script>
     }

Green.Health/Green.Health/Views/Order/comfirm_order.cshtml
@{
    ViewBag.Title = "comfirm_order";
}

@section PageSpecificStyleSheetIncludes{
    <style type="text/css">
    .comfirm-header {
    }

        .comfirm-flow {
            height:120px;
            display:block;
        }

        .receiver-info {
          display:block;
            
        }

        .address-list {
         width:1200px;
        }
        .addr {
            display: inline-block;
            vertical-align: top;
            position: relative;
            width: 237px;
            height: 100px;
            margin: 0 14px 0px 0;
            color: #666;
            cursor: pointer;
        }

        .inner {
            z-index: 2;
            position: relative;
            padding: 11px 15px;
            border:1px dashed;
            overflow: hidden;
        }
        h2 {
            display: block;
            font-size: 1.5em;
            -webkit-margin-before: 0.83em;
            -webkit-margin-after: 0.83em;
            -webkit-margin-start: 0px;
            -webkit-margin-end: 0px;
            font-weight: bold;
        }
        .pay-sytle a {
            display:inline-block;
            width:135px;
            height:35px;
            text-align:center;
            text-decoration:none;
            border:1px solid #8e8787;
        }
        .pay-info{display:block;}

       
     </style>
}
    
<div class="green-header-wrap-1240">
    <div class="comfirm-flow">
        
    </div>

    <div class="receiver-info">
      <h2>选择收货地址</h2>
        <div class="address-list" style="display:block">
            <div class="addr">
               <div class="inner">
                   <div class="addr-hd">
                       <span class="province">上海</span>
                       <span class="city">上海</span>
                       <span class="name">hanjun</span>
                   </div>
                   <div class="addr-bd">
                       <span class="dist">长宁</span>
                       <span class="town">新景</span>
                       <span class="street">金钟路968号 凌空SOHO 大楼15#</span>
                       <span class="phone">123456789</span>
                   </div>
               </div>
            </div>
        </div>
    </div>

    <div class="ctl">
        <button id="addnewaddress">使用新地址</button>
    </div>

    <div class="payInfo">
        <h4>支付方式</h4>
        <div class="pay-sytle">
            <a>支付宝</a>
        </div>
    </div>

    <h2>确认订单信息</h2>
    <div class="pro-detailinfo">
        <table>
            <colgroup>
                <col />
                <col />
                <col />
                <col />
            </colgroup>
            <tbody>
                <tr>
                    <td>
                        <p></p>
                        <p></p>
                        <p></p>
                        <p></p>
                    </td>
                    <td>
                       276 
                    </td>
                    <td>
                        1
                    </td>
                    <td>
                        276
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="payment-info">
        <p>
            <span>实收款</span>
            <span>¥</span>
            <span>276</span>
        </p>
    </div>

    <div class="submit-order">
        <button class="btn btn-success">提交订单</button>
    </div>
</div>

<div class="" style="display:none">

</div>

Green.Health/Green.Health/Views/Product/Detail.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "";
}

@section PageSpecificStyleSheetIncludes{
    <style>
        .sli {
            width: 100%;
            margin-top: 30px;
        }

        .pro-left {
            display: block;
            float: left;
            position: relative;
            width: 50%;
        }

        .pro-right {
            display: block;
            float: right;
            position: relative;
            width: 50%;
        }

        .big-img {
            display: block;
            width: 529px;
            height: 530px;
            background-repeat: no-repeat;
            background-position: center center;
            background-image: url("/Assets/Img/bigimg.png");
        }

        .pro-right pr-til {
            width: 100%;
            float: left;
            color: #3e3e3e;
            font-size: 24px;
            line-height: 25px;
            font-weight: normal;
        }

        .pr-price {
            width: 100%;
            float: left;
            color: #e30500;
            font-size: 32px;
            line-height: 36px;
            font-weight: normal;
            margin-top: 25px;
        }

        .pro-yunfee {
            width: 100%;
            float: left;
            padding-top: 8px;
            color: #808080;
        }

        .lbl-info {
            float: left;
            line-height: 42px;
        }

        .num-wrap .pro-addwrap {
            display: inline-block;
            float: left;
        }

        .pro-addwrap {
            border: 1px solid #a6a6a6;
        }

        .st-main {
            width: 386px;
            position: relative;
            float: left;
        }

        .l1 {
            padding-top: 30px;
            overflow: hidden;
            padding-left: 6px;
            padding-bottom: 10px;
        }

        .l2 {
            padding-top: 20px;
            padding-bottom: 20px;
        }

        .l3 {
            padding-top: 28px;
            padding-bottom: 15px;
        }

        .pro-addwrap .minus, .pro-addwrap .plus {
            display: inline-block;
            line-height: 28px;
            width: 28px;
            text-align: center;
            font-size: 18px;
            text-decoration: none;
        }

        .minus {
            border-right: 1px solid #a6a6a6;
        }

        .plus {
            border-left: 1px solid #a6a6a6;
        }

        .pro-addwrap .input {
            display: inline-block;
            line-height: 28px;
            width: 32px;
            text-align: center;
            font-size: 18px;
        }


        .ver-wrap .ver-addwrap {
            display: inline-block;
            border: 1px solid #4faf33;
            text-align: center;
            color: #666;
            text-decoration: none;
            padding: 10px 20px;
        }

        .ver-wrap, .num-wrap {
            margin-left: 70px;
        }

        .clear {
            clear: both;
            width: 0px;
            height: 0px;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }

        .sml-img {
            width: 530px;
            height: 80px;
            line-height: 80px;
            float: left;
            text-align: center;
            margin-top: 20px;
        }

            .sml-img a {
                width: 80px;
                height: 80px;
                float: left;
                display: inline-block;
                overflow: hidden;
                border: 1px solid #ddd;
                text-decoration:none;
            }

        .narrow-img {
        margin-left:32px;
        }

        .narrow-img-current {
            border: 1px solid #9ccf8d;
        }
        
    </style>
}

<div class="sli">
    <div class="green-header-wrap-1240">

        <div class="pro-left">
            <div class="big-img"></div>
            <div class="sml-img">
              <a href="javascript:void(null)" class="narrow-img narrow-img-current"></a>
              <a href="javascript:void(null)" class="narrow-img"></a>
              <a href="javascript:void(null)" class="narrow-img"></a>
              <a href="javascript:void(null)" class="narrow-img"></a>
            </div>
        </div>

        <div class="pro-right">
            <div class="st-main">
                <h1 class="pr-til">Title</h1>
                <h2 class="pr-price">2699</h2>
                <h5 class="pro-yunfee">运费:10元</h5>
                <div class="pro-info">
                    <div class="l1">
                        <span class="lbl-info">规格</span>
                        <div class="ver-wrap">
                            <a href="javascript:void();" class="ver-addwrap">500g</a>
                        </div>
                    </div>
                </div>
                <div class="pro-info">
                    <div class="l1 l2">
                        <span class="lbl-info">数量</span>
                        <ul class="num-wrap">
                            <li class="pro-addwrap">
                                <a href="javascript:void()" class="minus">-</a>
                                <span class="input">1</span>
                                <a href="javascript:void()" class="plus">+</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="pro-info">
                    <div class="l3">
                        <button type="button" class="btn btn-success btn-lg" id="btn-buy">立刻购买</button>
                        <button type="button" class="btn btn-default btn-lg" id="btn-addshopcar">加入购物车</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="productid"/>

@section PageSpecificJavascriptIncludes{
    <script>
        $("#btn-buy").bind('click', function (e) {
            window.location.href = "/Order/comfirm_order";
        });

        $("#btn-addshopcar").bind('click', function (e) {
            
        });
    </script>
}

Green.Health/Green.Health/Views/Shared/_Footer.cshtml
<div id="footer">
    <div id="helper">

    </div>
    <div id="support">

    </div>

    <div id="us">

    </div>
</div>

Green.Health/Green.Health/Views/Shared/_Head.cshtml
@model Green.Health.Models.CommonModel
<div class="green-header-wrap-1240">
    <div class="green-header-logo">
        <a href="#" class="health-green-logo-img"></a>
    </div>
    <div class="green-head-log">
        <ul class="green-log">
            @if (Model.Customer == null)
            {
                <li class="log-trigger" id="unlogin">
                    <a href="javascript:void();">
                        <img src="~/Assets/Img/person.png" />
                        <img src="~/Assets/Img/log-arrow.png" />
                    </a>
                    <div class="u-box" style="display: none;"></div>
                    <ul class="log-dropdown" style="display: none">
                        <li>
                            <button class="btn btn-success" id="btn_in">立即登录</button>
                        </li>
                        <li>
                            <a href="#">立即注册</a>
                        </li>
                        <li>
                            <a href="#">我的购物车</a>
                        </li>
                        <li>
                            <a href="#">我的订单</a>
                        </li>
                    </ul>
                </li>
            }
            else
            {
                <li class="log-trigger" id="islogin" style="display:block">
                    <a href="javascript:void();">
                        <img src="~/Assets/Img/person.png" />
                        <img src="~/Assets/Img/log-arrow.png" />
                    </a>
                    <div class="u-box" style="display: none;"></div>
                    <ul class="log-dropdown">
                        <li><a href="#">个人中心</a></li>
                        <li><a href="#">我的购物车</a></li>
                        <li><a href="#">我的订单</a></li>
                        <li><button class="btn btn-success" id="btn_out">退出</button></li>
                    </ul>
                </li>
            }
        </ul>
    </div>
</div>

Green.Health/Green.Health/Views/Shared/_Layout.cshtml
<!DOCTYPE>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
    <link rel="stylesheet" href="~/Assets/CSS/main.css"/>
    <link rel="stylesheet" href="~/Assets/CSS/BootStrap/css/bootstrap.css"/>
    @RenderSection("PageSpecificStyleSheetIncludes", required: false)
</head>

<body>

<div class="green-header">
    @*@Html.Partial("_Head")*@
    @Html.Action("headlink","Common")
</div>

<div class="content">
    @RenderBody()
</div>

<div class="footer">
    @Html.Partial("_Footer")
</div>
    <script src="~/Assets/JS/jquery-1.8.3.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(".log-trigger").hover(function () {
            $('.u-box').show();
            $('.log-dropdown').show();
        }, function () {
            $('.u-box').hide();
            $('.log-dropdown').hide();
        })
        $("#btn_in").bind('click', function (e) {
            window.location.href = "/Login/Index";
        });
        $("#btn_out").bind('click', function (e) {
            window.location.href = "/Login/LogOut";
        });
    </script>
    @RenderSection("PageSpecificJavascriptIncludes", required: false)
</body>

</html>

Green.Health/Green.Health/Views/Shared/_neck.cshtml
<div class="product_name">
    <span>玛卡</span>
</div>
<div class="desp">
    <ul>
        <li>产品信息</li>
        <li>产地来源</li>
        <li>产品品种</li>
    </ul>
</div>
<div class="buynow">
    <button>众筹订购</button>
</div>